<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <Version>1.0.0</Version>
    <Product>Tenveo PTZ Controller</Product>
    <Company>Tenveo PTZ Controller contributors</Company>
    <Copyright>Copyright (c) Tenveo PTZ Controller contributors</Copyright>
  </PropertyGroup>
</Project>
